# params.yaml
index_col: 'customer_id'
target_col: 'target'
one_hot_drop: 'if_binary'
auto_class_weights: 'Balanced'
test_size: 0.2
random_state: 42
n_splits: 5
metrics: ['f1', 'roc_auc']
n_jobs: -1
retrain: True
classification_threshold: 0.6
is_preprocessing: False
is_extend: False
# MLflow parameters
is_save_model: False
tracking_uri: "http://127.0.0.1:5003"
experiment_name: "churn_model_experiment"
run_name: "initial_data_model_run"
registry_model_name: "churn_model_initial_data"